#include "exec/helper.h"

#include "all-instr.h"

typedef int (*helper_fun)(swaddr_t);
make_helper(op_plus);


/* TODO: Add more instructions!!! */

helper_fun opcode_table [256] = {
/* 0x00 */	inv, add_rm2m_v, add_rm2r_v, add_rm2r_v, 
/* 0x04 */	inv, add_i2a_l, inv, inv, 
/* 0x08 */	inv, or_r_l, inv, inv, 
/* 0x0c */	inv, or_r2i_v, inv, op_plus, 
/* 0x10 */	inv, adc_r2r_l, inv, inv, 
/* 0x14 */	inv, inv, inv, inv, 
/* 0x18 */	inv, sbb_r2r_l, inv, inv, 
/* 0x1c */	inv, inv, inv, inv, 
/* 0x20 */	inv, and_r2rm_v, inv, inv, 
/* 0x24 */	inv, and_r2i_v, inv, inv,
/* 0x28 */	inv, sub_r2rm_v, inv, sub_rm2r_v, 
/* 0x2c */	inv, inv, inv, inv, 
/* 0x30 */	inv, xor_r_l, inv, inv, 
/* 0x34 */	inv, inv, inv, inv,
/* 0x38 */	cmp_r2r_b, cmp_r2r_v, cmp_rm2r_b, cmp_rm2r_v, 
/* 0x3c */	cmp_a2i_b, cmp_a2i_v, inv, inv, 
/* 0x40 */	inc_r_v, inc_r_v, inc_r_v, inc_r_v, 
/* 0x44 */	inc_r_v, inc_r_v, inc_r_v, inc_r_v,
/* 0x48 */	dec_r_v, dec_r_v, dec_r_v, dec_r_v, 
/* 0x4c */	dec_r_v, dec_r_v, dec_r_v, dec_r_v, 
/* 0x50 */	push_r_l, push_r_l, push_r_l, push_r_l, 
/* 0x54 */	push_r_l, push_r_l, push_r_l, push_r_l,
/* 0x58 */	pop_r_l, pop_r_l, pop_r_l, pop_r_l, 
/* 0x5c */	pop_r_l, pop_r_l, pop_r_l, pop_r_l, 
/* 0x60 */	pusha, popa, inv, inv,
/* 0x64 */	inv, inv, data_size, inv,
/* 0x68 */	push_i_l, imul_ilr2r_l, push_i_b, imul_ibr2r_l, 
/* 0x6c */	inv, inv, inv, inv, 
/* 0x70 */	inv, inv, jb_b, jae_b,
/* 0x74 */	jmp_e_b, jne_b, jbe_b, ja_b,
/* 0x78 */	js_b, inv, inv, inv, 
/* 0x7c */	jl_b, jge_b, jle_b, jg_b, 
/* 0x80 */	cmp_add_b, cmp_add_v, nemu_trap, mis_i2rm_v,
/* 0x84 */	test_r2r_b, test_r_l, inv, inv, 
/* 0x88 */	mov_r2rm_b, mov_r2rm_v, mov_rm2r_b, mov_rm2r_v,
/* 0x8c */	inv, lea_m2r_v, mov_rm2sr_v, inv, 
/* 0x90 */	xchg_a2r_v, xchg_a2r_v, xchg_a2r_v, xchg_a2r_v,
/* 0x94 */	xchg_a2r_v, xchg_a2r_v, xchg_a2r_v, xchg_a2r_v,
/* 0x98 */	inv, inv, inv, inv, 
/* 0x9c */	inv, inv, inv, inv, 
/* 0xa0 */	mov_moffs2a_b, mov_moffs2a_v, mov_a2moffs_b, mov_a2moffs_v,

/* 0xa4 */	inv, inv, inv, inv,
/* 0xa8 */	test_i2a_b, test_i2a_v, inv, inv,
/* 0xac */	inv, inv, inv, inv,
/* 0xb0 */	mov_i2r_b, mov_i2r_b, mov_i2r_b, mov_i2r_b,
/* 0xb4 */	mov_i2r_b, mov_i2r_b, mov_i2r_b, mov_i2r_b,
/* 0xb8 */	mov_i2r_v, mov_i2r_v, mov_i2r_v, mov_i2r_v, 
/* 0xbc */	mov_i2r_v, mov_i2r_v, mov_i2r_v, mov_i2r_v, 
/* 0xc0 */	inv, sft_rl_b, ret_iw, ret,
/* 0xc4 */	inv, inv, mov_i2rm_b, mov_i2rm_v,
/* 0xc8 */	inv, leave_l, inv, inv,
/* 0xcc */	int3, intx, inv, iret,
/* 0xd0 */	inv, inv, inv, sft_cb_rl,
/* 0xd4 */	inv, inv, inv, inv,
/* 0xd8 */	inv, inv, inv, inv,
/* 0xdc */	inv, inv, inv, inv,
/* 0xe0 */	inv, inv, inv, inv,
/* 0xe4 */	inv, inv, inv, inv,
/* 0xe8 */	call_i_l, jmp_l, ljmp, jmp_b,
/* 0xec */	inv, inv, inv, inv,
/* 0xf0 */	inv, inv, inv, rep_v,
/* 0xf4 */	inv, inv, test_rm2r_v, op_no2rm_v,
/* 0xf8 */	inv, inv, cli, inv,
/* 0xfc */	cld, inv, inv, uct_nr_v
};

helper_fun op_plus_table[256] = {
/* 0x00 */	inv, l_dt_v, inv, inv, 
/* 0x04 */	inv, inv, inv, inv, 
/* 0x08 */	inv, inv, inv, inv, 
/* 0x0c */	inv, inv, inv, inv, 
/* 0x10 */	inv, inv, inv, inv, 
/* 0x14 */	inv, inv, inv, inv, 
/* 0x18 */	inv, inv, inv, inv, 
/* 0x1c */	inv, inv, inv, inv, 
/* 0x20 */	mov_cr2gr_v, inv, mov_gr2cr_v, inv, 
/* 0x24 */	inv, inv, inv, inv,
/* 0x28 */	inv, inv, inv, inv, 
/* 0x2c */	inv, inv, inv, inv, 
/* 0x30 */	inv, inv, inv, inv, 
/* 0x34 */	inv, inv, inv, inv,
/* 0x38 */	inv, inv, inv, inv, 
/* 0x3c */	inv, inv, inv, inv, 
/* 0x40 */	inv, inv, inv, inv, 
/* 0x44 */	cmove_rm2r_v, inv, inv, cmova_rm2r_v,
/* 0x48 */	cmovs_rm2r_v, inv, inv, inv, 
/* 0x4c */	inv, cmovge_rm2r_v, inv, inv, 
/* 0x50 */	inv, inv, inv, inv, 
/* 0x54 */	inv, inv, inv, inv,
/* 0x58 */	inv, inv, inv, inv, 
/* 0x5c */	inv, inv, inv, inv, 
/* 0x60 */	inv, inv, inv, inv,
/* 0x64 */	inv, inv, inv, inv,
/* 0x68 */	inv, inv, inv, inv, 
/* 0x6c */	inv, inv, inv, inv, 
/* 0x70 */	inv, inv, inv, inv,
/* 0x74 */	inv, inv, inv, inv,
/* 0x78 */	inv, inv, inv, inv, 
/* 0x7c */	inv, inv, inv, inv, 
/* 0x80 */	inv, inv, inv, inv,
/* 0x84 */	je_l, jne_l, jbe_l, ja_l, 
/* 0x88 */	js_l, inv, inv, inv,
/* 0x8c */	jl_l, inv, jle_l, jg_l, 
/* 0x90 */	inv, inv, inv, inv,
/* 0x94 */	sete, setne, inv, inv,
/* 0x98 */	inv, inv, inv, inv, 
/* 0x9c */	inv, inv, inv, inv, 
/* 0xa0 */	inv, inv, inv, inv,
/* 0xa4 */	inv, inv, inv, inv,
/* 0xa8 */	inv, inv, inv, inv,
/* 0xac */	inv, inv, inv, imul_rm2r_l,
/* 0xb0 */	inv, inv, inv, inv,
/* 0xb4 */	inv, inv, mov_zb_v, mov_zw_l,
/* 0xb8 */	inv, inv, inv, inv,
/* 0xbc */	inv, inv, mov_rm2r_sbv, mov_rm2r_swv,
/* 0xc0 */	inv, inv, inv, inv,
/* 0xc4 */	inv, inv, inv, inv,
/* 0xc8 */	inv, inv, inv, inv,
/* 0xcc */	inv, inv, inv, inv,
/* 0xd0 */	inv, inv, inv, inv,
/* 0xd4 */	inv, inv, inv, inv,
/* 0xd8 */	inv, inv, inv, inv,
/* 0xdc */	inv, inv, inv, inv,
/* 0xe0 */	inv, inv, inv, inv,
/* 0xe4 */	inv, inv, inv, inv,
/* 0xe8 */	inv, inv, inv, inv,
/* 0xec */	inv, inv, inv, inv,
/* 0xf0 */	inv, inv, inv, inv,
/* 0xf4 */	inv, inv, inv, inv,
/* 0xf8 */	inv, inv, inv, inv,
/* 0xfc */	inv, inv, inv, inv
};

make_helper(exec) {
	return opcode_table[ instr_fetch(eip, 1) ](eip);
}

make_helper(op_plus){
	return op_plus_table[ instr_fetch(eip+1,1) ](eip);
}

